name: Secure CI/CD Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  # Job para instalar dependências, rodar linting e testes
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linting (flake8)
      run: |
        pip install flake8
        flake8 bg_remove.py
    
    - name: Run tests (se existirem)
      run: |
        pip install pytest
        pytest
    
  # Job para rodar CodeQL
  codeql:
    runs-on: ubuntu-latest
    name: Perform CodeQL Analysis
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
    
    - name: Run CodeQL
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security'
    
  # Job para escaneamento de dependências com Dependabot
  dependabot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Dependabot
      uses: dependabot/fetch-metadata@v1
    
    - name: Run Dependabot to check dependencies
      run: |
        dependabot update --all
    
    - name: Check for security vulnerabilities in dependencies
      run: |
        pip install bandit
        bandit -r .
