name: Secure CI/CD Workflow

permissions:
  contents: read
  security-events: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint_summary: ${{ steps.lint_step.outputs.summary }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run linting (flake8)
        id: lint_step
        run: |
          pip install flake8
          flake8 bg_remove.py > lint_output.txt 2>&1 || true
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat lint_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    outputs:
      test_summary: ${{ steps.test_step.outputs.summary }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests (pytest)
        id: test_step
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings > test_output.txt 2>&1 || true
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat test_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  codeql:
    runs-on: ubuntu-latest
    name: Perform CodeQL Analysis
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: 'security'

  dependabot:
    if: contains(github.event.pull_request.user.login, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Dependabot
        uses: dependabot/fetch-metadata@v1
      
      - name: Run Dependabot to check dependencies
        run: |
          dependabot update --all
      
      - name: Check for security vulnerabilities in dependencies
        run: |
          pip install bandit
          bandit -r .

  summary:
    runs-on: ubuntu-latest
    needs: [lint, test, codeql]
    steps:
      - name: Send summary to Discord
        env:
          # Ajuste o segredo conforme o nome configurado no seu repositório
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          # Captura os outputs dos jobs de lint e teste
          LINT_SUMMARY: ${{ needs.lint.outputs.lint_summary }}
          TEST_SUMMARY: ${{ needs.test.outputs.test_summary }}
        run: |
          # Caso o LINT_SUMMARY esteja vazio, definimos uma mensagem padrão
          if [ -z "$LINT_SUMMARY" ]; then
            LINT_SUMMARY="No linting issues."
          fi

          # Monta a mensagem de forma que cada bloco de código (``` ... ```) 
          # fique em linhas separadas
          SUMMARY_MESSAGE="**Workflow Summary**\n\n"\
          "**Lint Results:**\n"\
          "\`\`\`\n${LINT_SUMMARY}\n\`\`\`\n\n"\
          "**Test Results:**\n"\
          "\`\`\`\n${TEST_SUMMARY}\n\`\`\`"

          echo "Sending summary to Discord..."
          echo "Summary message (raw):"
          printf '%s\n' "$SUMMARY_MESSAGE"

          # Gera JSON válido usando jq, preservando newlines exatamente como estão
          payload="$(printf '%s' "$SUMMARY_MESSAGE" | jq -Rs '{content: .}')"
          echo "Payload: $payload"

          # Envia o payload para o Discord
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               "$DISCORD_WEBHOOK_URL"

        